In [1]:
import xarray as xr
import numpy as np
import collocate

### Curvilinear grid (Works) 

In [2]:
# 
da_latlon_as_grid = xr.DataArray(np.arange(100).reshape(10, 10), 
                  dims=('x','y'),
                  coords={'latitude':(('x','y'),np.arange(100).reshape(10, 10)),
                  'longitude':(('x','y'),np.arange(100).reshape(10, 10))})
da_latlon_as_grid

<xarray.DataArray (x: 10, y: 10)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
Coordinates:
    latitude   (x, y) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
    longitude  (x, y) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
Dimensions without coordinates: x, y

In [3]:
pt1 = da_latlon_as_grid.isel(x=slice(0,4),y=3)
collocate.collocate(pt1, da_latlon_as_grid, h_sep=1)

<xarray.Dataset>
Dimensions:    (x: 4)
Coordinates:
  * x          (x) int64 0 1 2 3
Data variables:
    latitude   (x) int64 3 13 23 33
    longitude  (x) int64 3 13 23 33
    var        (x) float64 3.0 13.0 23.0 33.0

### Ortho grid with dummy dims (x & y) (Works) 

In [4]:
da_latlon_as_arrays = xr.DataArray(np.arange(100).reshape(10, 10), 
                  dims=('x','y'),
                  coords={'latitude':(('y'),np.arange(0,10)),
                  'longitude':(('x'),np.arange(0,10))})
da_latlon_as_arrays

<xarray.DataArray (x: 10, y: 10)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
Coordinates:
    latitude   (y) int64 0 1 2 3 4 5 6 7 8 9
    longitude  (x) int64 0 1 2 3 4 5 6 7 8 9
Dimensions without coordinates: x, y

In [5]:
pt2 = da_latlon_as_arrays.isel(x=slice(0,4),y=3)
collocate.collocate(pt2, da_latlon_as_arrays, h_sep=1)

<xarray.Dataset>
Dimensions:    (x: 4)
Coordinates:
  * x          (x) int64 0 1 2 3
Data variables:
    latitude   (x) int64 3 3 3 3
    longitude  (x) int64 0 1 2 3
    var        (x) float64 3.0 13.0 23.0 33.0

### Ortho grid with latitude and longitude as dims (Does NOT work) 

In [6]:
da_latlon_as_dims = xr.DataArray(np.arange(100).reshape(10, 10), 
                  dims=('longitude','latitude'),
                  coords={'latitude':np.arange(0,10),
                  'longitude':np.arange(0,10)})
da_latlon_as_dims

<xarray.DataArray (longitude: 10, latitude: 10)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
Coordinates:
  * latitude   (latitude) int64 0 1 2 3 4 5 6 7 8 9
  * longitude  (longitude) int64 0 1 2 3 4 5 6 7 8 9

In [7]:
pt3 = da_latlon_as_dims.isel(longitude=slice(0,4),latitude=3)
collocate.collocate(pt3, da_latlon_as_dims, h_sep=1)

KeyError: "['latitude' 'longitude'] not in index"

### Fix above dataset by swaping dummy x/y vars for longitude/latitude

In [8]:
# Fix dims
da_latlon_fixed = da_latlon_as_dims

da_latlon_fixed.coords['x'] = xr.DataArray(np.arange(0,10), dims='longitude')
da_latlon_fixed.coords['y'] = xr.DataArray(np.arange(0,10), dims='latitude')

da_latlon_fixed = da_latlon_fixed.swap_dims({'longitude':'x','latitude':'y'})
da_latlon_fixed

<xarray.DataArray (x: 10, y: 10)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
Coordinates:
    latitude   (y) int64 0 1 2 3 4 5 6 7 8 9
    longitude  (x) int64 0 1 2 3 4 5 6 7 8 9
  * x          (x) int64 0 1 2 3 4 5 6 7 8 9
  * y          (y) int64 0 1 2 3 4 5 6 7 8 9

In [9]:
pt4 = da_latlon_fixed.isel(x=slice(0,4),y=3)
pt4

<xarray.DataArray (x: 4)>
array([ 3, 13, 23, 33])
Coordinates:
    latitude   int64 3
    longitude  (x) int64 0 1 2 3
  * x          (x) int64 0 1 2 3
    y          int64 3

In [10]:
collocate.collocate(pt4, da_latlon_fixed, h_sep=1)

<xarray.Dataset>
Dimensions:    (x: 4)
Coordinates:
  * x          (x) int64 0 1 2 3
Data variables:
    latitude   (x) int64 3 3 3 3
    longitude  (x) int64 0 1 2 3
    y          (x) int64 3 3 3 3
    var        (x) float64 3.0 13.0 23.0 33.0